### ISSUE TITLE
LocaleReceiver Gives SyntaxError: Cannot use import statement outside a module in Nextjs

### ISSUE THREAD

**Issue by samyarkd** [nanxiaobei/antd-img-crop#222]
When I install **antd-img-crop** and use it on my **Next.js** app it gives the following error: 
```
import LocaleReceiver from '../locale/LocaleReceiver';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (F:\samyar\react\gharardad-pardaz\node_modules\antd-img-crop\dist\antd-img-crop.cjs.js:21:22)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

> Build error occurred
Error: Failed to collect page data for /app/profile
    at F:\samyar\react\gharardad-pardaz\node_modules\next\dist\build\utils.js:960:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

Steps to reproduce: 

1. Use Next.js
2. Install `antd-img-crop`
3. Use it in a page
4. build the app `npm run build`
5. you should see the error

Link of Stackblitz : [Stackblitz](https://stackblitz.com/edit/nextjs-xwj7uz?file=pages/index.js)

**Comment by nanxiaobei** [comment]
with the PR and updated to `4.6.0`.
